# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Builder
    # Steps represent a sequence of tasks that will be executed as part of the job
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: https://discord.com/api/webhooks/770461531275526154/kTXek3InBLcK0jAidMBbXPH8_uu_tq_20F-aWAdlEuvuoYCXYa1h4YNj-tvKUp9yIU7c
        if: failure()

      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.2
        with:
          webhook: https://discord.com/api/webhooks/770461459753861150/yfScFu85AouutAC9NJ9b-LtJRvhVFUIDExyJiZF3KRCy8GxC5bh028XOfiqJL9E1b4uU
          message: "Successful commit to **{{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}**.\nDiff: {{ github.context.payload.compare }}"
          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'
